// vcsRepoScaffoldWorkflow — M6c. Builds the seed-file set for a new project's
// repo and (when execute is called) ships them to Bitbucket via the
// configured VcsProvider. The seed set draws from velocity-ops content:
// CONTEXT.md from project-brief, AGENTS.md from selected agent role cards,
// CLAUDE.md baseline, .husky/pre-commit + .claude/hooks/* from atl-mcp's own
// quality stack, ADR seeds + requirements scaffold from the blueprint.

import type { ProjectBlueprint } from "../domain/projectBlueprint.js";
import type {
  VelocityAgentSlug,
  VelocityContentRegistry,
  VelocityModuleSlug,
} from "../velocity/contentRegistry.js";
import type { VcsProvider } from "../providers/vcs/VcsProvider.js";
import { renderTemplate, type TemplateVariables } from "../velocity/templateRenderer.js";

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
  readonly executable?: boolean;
}

export interface VcsScaffoldInput {
  readonly workspace: string;
  readonly repoSlug: string;
  /** Agent role-card slugs to include in the new repo's AGENTS.md. */
  readonly agentRoles?: readonly VelocityAgentSlug[];
  /**
   * Stack module slugs to append to the new repo's CLAUDE.md, one section per
   * module. The operator picks these up-front (e.g. "nextjs-15", "drizzle-orm").
   * Empty array → CLAUDE.md ships with the baseline only.
   */
  readonly stackChoices?: readonly VelocityModuleSlug[];
  /** Optional override variables for template rendering. */
  readonly variables?: TemplateVariables;
}

export interface VcsPreviewResult {
  readonly files: readonly ScaffoldFile[];
  readonly totalBytes: number;
}

export interface VcsExecuteResult {
  readonly repoUrl: string;
  readonly defaultBranch: string;
  readonly filesSeeded: number;
  readonly alreadyExisted: boolean;
  readonly initialCommitId?: string;
}

export interface VcsRepoScaffoldWorkflow {
  preview(blueprint: ProjectBlueprint, input: VcsScaffoldInput): Promise<VcsPreviewResult>;
  execute(blueprint: ProjectBlueprint, input: VcsScaffoldInput): Promise<VcsExecuteResult>;
}

const DEFAULT_AGENT_ROLES: readonly VelocityAgentSlug[] = [
  "architect", "implementer", "tester", "reviewer", "tdd-coach", "docs", "ops",
];

export function createVcsRepoScaffoldWorkflow(deps: {
  readonly registry: VelocityContentRegistry;
  readonly vcs: VcsProvider;
}): VcsRepoScaffoldWorkflow {
  async function buildScaffoldFiles(blueprint: ProjectBlueprint, input: VcsScaffoldInput): Promise<readonly ScaffoldFile[]> {
    const vars: TemplateVariables = {
      project_name: blueprint.name,
      PROJECT: blueprint.key,
      project_key: blueprint.key,
      "Project Name": blueprint.name,
      ...(input.variables ?? {}),
    };

    // CONTEXT.md from project-brief.
    const briefBody = await deps.registry.readTemplate("project-brief");
    const renderedBrief = renderTemplate(briefBody, vars);
    const contextMd = `# CONTEXT — ${blueprint.name}\n\nGenerated by atl-mcp from blueprint v${blueprint.blueprintVersion}.\n\n---\n\n${renderedBrief.text}\n`;

    // AGENTS.md — bundle the selected agent role cards.
    const agentSlugs = input.agentRoles ?? DEFAULT_AGENT_ROLES;
    const agentBodies = await Promise.all(agentSlugs.map(async (slug) => {
      const body = await deps.registry.readAgent(slug);
      return `## ${slug}\n\n${body}`;
    }));
    const agentsMd = [
      "# AGENTS",
      "",
      `This file is the agent contract for **${blueprint.name}** per the LF AGENTS.md specification.`,
      `Bundled role cards lifted by atl-mcp from velocity-ops-engine. Build agents adopt these personas during the work they do.`,
      "",
      "---",
      "",
      ...agentBodies,
    ].join("\n");

    // CLAUDE.md — baseline iron laws, anchored on atl-mcp's own conventions.
    const baselineClaudeLines = [
      `# Claude Code: ${blueprint.name} guidance`,
      "",
      `Generated by atl-mcp from blueprint v${blueprint.blueprintVersion}. Hand-edited by the operator after.`,
      "",
      "## What this project is",
      "",
      `${blueprint.name} (key: \`${blueprint.key}\`). See \`CONTEXT.md\` for the full charter.`,
      "",
      "## Operating rules",
      "",
      "- **No completion claims without verification evidence.** Tests pass before claiming done.",
      "- **No production code without a failing test first.** Write the test, watch it fail, then implement.",
      "- **Keep modules focused.** Split when reviewability or ownership improves.",
      "- **ADRs in MADR format** in `docs/adr/`. Architectural decisions need a record.",
      "",
      "## Where I am in the build",
      "",
      "Check `docs/adr/` for the latest decision records. The blueprint that seeded this repo lives in atl-mcp.",
    ];
    // Append one section per chosen stack module so the build agent has the
    // stack-specific guidance inline.
    const stackChoices = input.stackChoices ?? [];
    if (stackChoices.length > 0) {
      baselineClaudeLines.push("", "---", "", "# Stack guidance");
      for (const slug of stackChoices) {
        const moduleBody = await deps.registry.readModule(slug);
        baselineClaudeLines.push("", `## Stack: ${slug}`, "", moduleBody);
      }
    }
    const claudeMd = baselineClaudeLines.join("\n");

    // CONTRIBUTING.md from the contributing template.
    const contributingBody = await deps.registry.readTemplate("contributing");
    const contributingMd = renderTemplate(contributingBody, vars).text;

    // git-branching.md from the template.
    const branchingBody = await deps.registry.readTemplate("git-branching");
    const branchingMd = renderTemplate(branchingBody, vars).text;

    // ADR 0000 — seed the ADR process from the velocity ADR template.
    const adrTemplate = await deps.registry.readTemplate("architecture-decision");
    const adr0000 = [
      "---",
      "status: accepted",
      `date: ${new Date().toISOString().slice(0, 10)}`,
      "deciders: [project-team]",
      "---",
      "",
      "# 0000. Use ADRs to record architecture decisions",
      "",
      "## Context",
      "",
      "Architecture decisions need a durable record. This project uses MADR-format ADRs in `docs/adr/`.",
      "",
      "## Decision",
      "",
      "Adopt MADR. Use the template below for every new architecture decision.",
      "",
      "---",
      "",
      "## Template",
      "",
      adrTemplate,
    ].join("\n");

    // .ai/requirements.md — the requirements catalog template, populated with
    // a stub from the blueprint's requirements list.
    const requirementsBody = await deps.registry.readTemplate("requirements-catalog");
    const requirementsMd = [
      "# Requirements Catalog",
      "",
      `Seeded from atl-mcp blueprint v${blueprint.blueprintVersion}. Refine in place.`,
      "",
      "## From blueprint",
      "",
      blueprint.requirements.length === 0
        ? "_No requirements yet — fill in during M4 blueprint synthesis._"
        : blueprint.requirements.map((r, i) => `${i + 1}. **${r.id ?? `REQ-${i + 1}`}** — ${r.title ?? "(untitled)"}`).join("\n"),
      "",
      "---",
      "",
      "## Template reference",
      "",
      requirementsBody,
    ].join("\n");

    // .husky/pre-commit — atl-mcp's own pre-commit gate, adapted for project use.
    const huskyPreCommit = `#!/usr/bin/env sh
# Pre-commit gate. Add project-specific checks above the default chain.
set -eu

if [ -f package.json ] && grep -q '"typecheck"' package.json 2>/dev/null; then
  echo '[pre-commit] Running typecheck...'
  npm run typecheck
fi

if [ -f package.json ] && grep -q '"test"' package.json 2>/dev/null; then
  echo '[pre-commit] Running tests...'
  npm test
fi

# Block staged files larger than 1 MiB.
LARGE_FILES="$(git diff --cached --name-only --diff-filter=ACMR | while IFS= read -r file; do [ -f "$file" ] || continue; bytes=$(wc -c < "$file" | tr -d ' '); if [ "$bytes" -gt 1048576 ]; then printf '%s\\n' "$file"; fi; done)"
if [ -n "$LARGE_FILES" ]; then
  echo '[pre-commit] Refusing commit with staged files larger than 1 MiB:' >&2
  printf '%s\\n' "$LARGE_FILES" >&2
  exit 1
fi
`;

    const readme = [
      `# ${blueprint.name}`,
      "",
      `Project key: \`${blueprint.key}\`. Provisioned by atl-mcp.`,
      "",
      "See:",
      "- [`CONTEXT.md`](CONTEXT.md) — system purpose, users, domains.",
      "- [`AGENTS.md`](AGENTS.md) — agent contract + role cards.",
      "- [`CLAUDE.md`](CLAUDE.md) — Claude Code guidance.",
      "- [`docs/adr/`](docs/adr/) — architecture decision records.",
      "- [`.ai/requirements.md`](.ai/requirements.md) — requirements catalog.",
    ].join("\n");

    return [
      { path: "README.md", content: readme + "\n" },
      { path: "CONTEXT.md", content: contextMd },
      { path: "AGENTS.md", content: agentsMd + "\n" },
      { path: "CLAUDE.md", content: claudeMd + "\n" },
      { path: "CONTRIBUTING.md", content: contributingMd + "\n" },
      { path: "docs/git-branching.md", content: branchingMd + "\n" },
      { path: "docs/adr/0000-adr-process.md", content: adr0000 + "\n" },
      { path: ".ai/requirements.md", content: requirementsMd + "\n" },
      { path: ".husky/pre-commit", content: huskyPreCommit, executable: true },
      { path: ".gitignore", content: "node_modules/\ndist/\n.env\n.env.local\n*.log\n" },
    ];
  }

  return {
    async preview(blueprint, input) {
      const files = await buildScaffoldFiles(blueprint, input);
      const totalBytes = files.reduce((sum, f) => sum + Buffer.byteLength(f.content, "utf8"), 0);
      return { files, totalBytes };
    },
    async execute(blueprint, input) {
      const files = await buildScaffoldFiles(blueprint, input);
      const repo = await deps.vcs.createRepository({
        workspace: input.workspace,
        slug: input.repoSlug,
        isPrivate: true,
      });
      if (repo.alreadyExisted) {
        return {
          repoUrl: repo.url,
          defaultBranch: repo.defaultBranch,
          filesSeeded: 0,
          alreadyExisted: true,
        };
      }

      let lastCommit: string | undefined;
      for (const file of files) {
        const result = await deps.vcs.putFile({
          workspace: input.workspace,
          repoSlug: input.repoSlug,
          branch: repo.defaultBranch,
          path: file.path,
          contents: file.content,
          commitMessage: `seed: ${file.path}`,
        });
        lastCommit = result.sha;
      }
      return {
        repoUrl: repo.url,
        defaultBranch: repo.defaultBranch,
        filesSeeded: files.length,
        alreadyExisted: false,
        ...(lastCommit ? { initialCommitId: lastCommit } : {}),
      };
    },
  };
}
