#!/usr/bin/env python3
"""Seed the ACO Confluence space with the 28-page IA from the build plan.

Idempotent: skips a page if a page with the same title already exists in ACO.
Reads ATLASSIAN_* env vars from the process environment (load from .env first).
"""
from __future__ import annotations

import json
import os
import sys
from base64 import b64encode
from urllib.request import Request, urlopen
from urllib.error import HTTPError


SITE = os.environ["ATLASSIAN_SITE_URL"].rstrip("/")
EMAIL = os.environ["ATLASSIAN_EMAIL"]
TOKEN = os.environ["ATLASSIAN_API_TOKEN"]
SPACE_KEY = "ACO"
SPACE_ID = "2588674"
HOMEPAGE_ID = "2588787"

AUTH = "Basic " + b64encode(f"{EMAIL}:{TOKEN}".encode()).decode()


def api(method: str, path: str, body: dict | None = None) -> dict:
    url = f"{SITE}{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = Request(url, data=data, method=method)
    req.add_header("Authorization", AUTH)
    req.add_header("Accept", "application/json")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urlopen(req, timeout=30) as r:
            raw = r.read()
            return json.loads(raw) if raw else {}
    except HTTPError as e:
        body_text = e.read().decode("utf-8", "replace")
        print(f"HTTP {e.code} on {method} {path}: {body_text[:600]}", file=sys.stderr)
        raise


def list_existing_titles() -> dict[str, str]:
    """Return {title: page_id} for every page in the space."""
    titles: dict[str, str] = {}
    cursor: str | None = None
    while True:
        path = f"/wiki/api/v2/spaces/{SPACE_ID}/pages?limit=100"
        if cursor:
            path += f"&cursor={cursor}"
        res = api("GET", path)
        for p in res.get("results", []):
            titles[p["title"]] = p["id"]
        next_link = res.get("_links", {}).get("next")
        if not next_link:
            break
        # Cursor is a query param in the next link; extract.
        if "cursor=" in next_link:
            cursor = next_link.split("cursor=", 1)[1].split("&", 1)[0]
        else:
            break
    return titles


def create_page(title: str, parent_id: str, body_storage: str) -> str:
    payload = {
        "spaceId": SPACE_ID,
        "status": "current",
        "title": title,
        "parentId": parent_id,
        "body": {"representation": "storage", "value": body_storage},
    }
    res = api("POST", "/wiki/api/v2/pages", payload)
    return res["id"]


# ---------------------------------------------------------------------------
# Page content templates
# ---------------------------------------------------------------------------

def stub(intro: str, related_links: list[str] | None = None) -> str:
    """Lightweight stub used for non-centerpiece pages."""
    body = f"<p>{intro}</p>"
    if related_links:
        body += "<h2>Related</h2><ul>" + "".join(f"<li>{l}</li>" for l in related_links) + "</ul>"
    body += '<p><em>This page is part of the Agent Context Orchestrator (ACO) seed space generated for the demo walkthrough. See the <a href="https://lateapexllc.atlassian.net/jira/software/projects/PCO/boards/1">PCO Jira project</a> for tracked work and <code>docs/demo/</code> in the GitHub repo for the mirrored content.</em></p>'
    return body


def project_overview() -> str:
    return """
<h1>Agent Context Orchestrator</h1>
<p><strong>One sentence:</strong> An MCP server that turns raw project requirements into agent-ready Jira, Confluence, and Bitbucket workspaces.</p>
<p>This Confluence space, and the linked Jira project <strong>PCO</strong>, were generated by the orchestrator from its own requirements. The dogfooding frame is the demonstration: a tool that produces project structures for engineering work has produced its own.</p>

<h2>Three docs are authoritative</h2>
<ol>
  <li><strong>The spec.</strong> <code>agent-context-orchestrator-mcp-plan-v6.md</code> in the GitHub repo (~2,400 lines).</li>
  <li><strong>The build sequence.</strong> <code>docs/build-orchestration.md</code> ties milestones M0 through M11 to partner integration guides.</li>
  <li><strong>The partner guides.</strong> 42 docs in <code>docs/partners/</code>, each backing a specific spec adoption point.</li>
</ol>

<h2>Reading order for reviewers</h2>
<ol>
  <li>This page.</li>
  <li><a href="#">Architecture Overview</a> &mdash; how the system is built.</li>
  <li><a href="#">Operational Runbook</a> &mdash; how it&rsquo;s run.</li>
  <li><a href="#">Audit Findings + Remediation Summary</a> &mdash; what I got wrong. Most signal-dense page.</li>
  <li><a href="#">Roadmap + Milestones</a> &mdash; what&rsquo;s done, what&rsquo;s next.</li>
</ol>

<h2>Where the code lives</h2>
<p><a href="https://github.com/">github.com/&lt;you&gt;/atl-mcp</a> &mdash; spec, partner guides, ADRs, source, tests, and the demo mirror under <code>docs/demo/</code>.</p>

<h2>Linked artifacts</h2>
<ul>
  <li>Jira project: <a href="https://lateapexllc.atlassian.net/jira/software/projects/PCO/boards/1">PCO board</a></li>
  <li>Spec: v6 (in repo, ~2,400 lines)</li>
  <li>ADRs: 6 records under <code>docs/adr/</code></li>
</ul>
"""


def product_brief() -> str:
    return """
<h1>Product Brief</h1>
<p><strong>TL;DR:</strong> Engineers and engineering teams produce projects in Jira/Confluence/Git. Doing this by hand is slow and inconsistent. atl-mcp turns a structured project profile into agent-ready Atlassian + VCS workspaces, deterministically.</p>

<h2>Problem</h2>
<p>When a new initiative starts, someone has to translate &ldquo;here&rsquo;s what we want to build&rdquo; into the artifacts that an engineering team and increasingly an agentic AI build agent need: epics, stories with acceptance criteria, Confluence pages with architecture and runbooks, a repo scaffold with branching conventions and an agent-context manifest. This work is mechanical but high-stakes &mdash; bad scaffolding propagates for months.</p>

<h2>Solution</h2>
<p>atl-mcp ingests a structured project profile and emits a complete Jira+Confluence+VCS workspace. The output is consumable by humans AND by agentic build agents (Claude Code, Cursor, etc.) via MCP. The same profile produces the same workspace; re-running is idempotent (v6 &sect;18).</p>

<h2>Users</h2>
<ul>
  <li><strong>Operators</strong> &mdash; the human who runs the orchestrator at project kickoff.</li>
  <li><strong>Build agents</strong> &mdash; agentic AI consumers that read context from the orchestrator&rsquo;s MCP surface (v6 &sect;14).</li>
  <li><strong>Reviewers</strong> &mdash; humans who review changes via Jira/Confluence/Bitbucket as usual.</li>
</ul>

<h2>Out of scope (v1)</h2>
<ul>
  <li>Persistent agent memory across sessions (deferred &mdash; v6 &sect;4 non-goals).</li>
  <li>Multi-tenant SaaS hosting (post-v1 &mdash; v6 &sect;7.3 documents the runway).</li>
  <li>GitHub, GitLab, Bitbucket Data Center / Server (post-v1 &mdash; v6 &sect;3 non-goals).</li>
</ul>
"""


def architecture_overview() -> str:
    return """
<h1>Architecture Overview</h1>
<p><strong>TL;DR:</strong> atl-mcp is an MCP server that ingests project requirements and emits agent-ready Jira + Confluence + Bitbucket workspaces. It runs on a dual-port HTTP transport (admin REST on one port, MCP streamable HTTP on the other &mdash; v6 &sect;22). Storage is Postgres in production and pglite in development (ADR-0001). Writes are gated by a policy decision layer (v6 &sect;7.2) and recorded in a hash-chained ed25519-signed audit log (v6 &sect;30.1).</p>

<h2>System context</h2>
<ac:structured-macro ac:name="info">
  <ac:rich-text-body><p>The system has three trust boundaries: external callers &rarr; server &rarr; external systems. Each boundary has explicit auth + audit obligations.</p></ac:rich-text-body>
</ac:structured-macro>

<h3>External callers</h3>
<ul>
  <li><strong>Build agents</strong> connect via MCP (stdio or streamable-HTTP). They authenticate at session start and request tools, resources, and prompts (v6 &sect;14).</li>
  <li><strong>Operators</strong> connect via the admin REST port for management actions (status, profile import, dry-run preview).</li>
</ul>

<h3>Server (atl-mcp)</h3>
<ul>
  <li><strong>MCP transport</strong> (<code>src/mcp/</code>) &mdash; session capability negotiation per v6 &sect;2.2, dual-port architecture per v6 &sect;22.2.</li>
  <li><strong>Domain model</strong> (<code>src/domain/</code>) &mdash; 18 typed entities including ProjectProfile, ContextPack, AuditEntry, PolicyDecision, TraceLink (v6 &sect;10).</li>
  <li><strong>Storage</strong> (<code>src/storage/</code>) &mdash; schema, migrations with rehearsal, repositories. ADR-0001.</li>
  <li><strong>Provider layer</strong> (<code>src/providers/</code>) &mdash; Atlassian (Jira+Confluence) and VCS (Bitbucket). Each provider implements capability discovery (v6 &sect;19).</li>
  <li><strong>Policy + audit</strong> (<code>src/security/</code>) &mdash; every state-changing op gates through the policy decision layer (v6 &sect;7.2) and emits an audit entry (v6 &sect;30.1).</li>
  <li><strong>Observability</strong> (<code>src/observability/</code>) &mdash; pino file logger; never writes to stdout because stdout carries JSON-RPC frames (CLAUDE.md operating rule).</li>
</ul>

<h3>External systems</h3>
<ul>
  <li><strong>Atlassian Cloud</strong> &mdash; Jira REST v3 + Confluence REST v2. Auth via API token or OAuth 3LO (v6 &sect;20). ADF and storage format both supported (ADR-0003).</li>
  <li><strong>Bitbucket Cloud</strong> &mdash; REST v2.0. Auth via app-password or OAuth (ADR-0004).</li>
  <li><strong>Webhook ingress</strong> &mdash; Atlassian and Bitbucket webhooks land via signed POST endpoints (v6 &sect;26).</li>
</ul>

<h2>Dataflow: requirement &rarr; provisioned workspace</h2>
<ol>
  <li><strong>Intake.</strong> Operator provides a project profile (structured JSON or markdown). The server validates against the ProjectProfile schema in <code>src/domain/projectProfile.ts</code>.</li>
  <li><strong>Preflight.</strong> Capability discovery runs against the live Atlassian + VCS targets to produce a preflight profile (<code>src/preflight/preflightWorkflow.ts</code>). Failures here block downstream work.</li>
  <li><strong>Blueprint.</strong> The blueprint workflow (M4) turns the profile into an epic-and-story plan via MCP sampling (v6 &sect;23). Output validated by an adversarial verification triplet (v6 &sect;18.1).</li>
  <li><strong>Plan.</strong> The provisioning planner diffs the blueprint against the live workspace state to produce an ordered, idempotent action list (v6 &sect;18, milestone M5).</li>
  <li><strong>Execute.</strong> The Jira executor (M6a) runs first &mdash; it&rsquo;s the first shippable slice. Confluence (M6b) and VCS (M6c) follow.</li>
  <li><strong>Audit.</strong> Every executor wraps its writes in <code>policyDecisionLayer.evaluate()</code> + <code>auditEntries.append()</code>. The audit chain is verifiable post-hoc.</li>
</ol>

<h2>Key tradeoffs</h2>
<table>
  <tr><th>Decision</th><th>Alternative</th><th>Why we chose it</th><th>Cost</th></tr>
  <tr><td>ADF as default Confluence body format (ADR-0003)</td><td>storage format only</td><td>JSON validates and round-trips cleanly</td><td>Dual renderer with ongoing maintenance</td></tr>
  <tr><td>Bitbucket app-password (ADR-0004)</td><td>OAuth 2.0 only</td><td>Simpler ops; no refresh races</td><td>Per-user tokens; manual rotation</td></tr>
  <tr><td>pglite for dev (ADR-0001)</td><td>sqlite, full Postgres</td><td>Real Postgres semantics, zero-config local</td><td>One more abstraction in the dev path</td></tr>
  <tr><td>noble-ciphers for token encryption (ADR-0002)</td><td>Node crypto, libsodium-wrappers</td><td>Audited primitives, pure-JS, no native build deps</td><td>Slightly slower than native</td></tr>
  <tr><td>Hash-chain + ed25519 audit (ADR-0005)</td><td>append-only with periodic snapshots</td><td>Tamper-evident with cheap verification</td><td>Single-tenant baked-in; multi-tenant requires refactor (v6 &sect;7.3)</td></tr>
  <tr><td>Single-message Task dispatch for parallel sub-agents</td><td>independent message-per-Task</td><td>Claude Code only parallelizes within a single message</td><td>Documentation overhead in CLAUDE.md</td></tr>
</table>

<h2>Where things live in the repo</h2>
<table>
  <tr><th>Concern</th><th>Path</th></tr>
  <tr><td>MCP transport</td><td><code>src/mcp/</code></td></tr>
  <tr><td>Domain types</td><td><code>src/domain/</code> (18 files)</td></tr>
  <tr><td>Storage</td><td><code>src/storage/</code> (schema, migrations, repositories)</td></tr>
  <tr><td>Atlassian providers</td><td><code>src/providers/atlassian/</code></td></tr>
  <tr><td>VCS provider</td><td><code>src/providers/vcs/</code></td></tr>
  <tr><td>Security primitives</td><td><code>src/security/</code></td></tr>
  <tr><td>Observability</td><td><code>src/observability/logger.ts</code></td></tr>
  <tr><td>Preflight</td><td><code>src/preflight/preflightWorkflow.ts</code></td></tr>
  <tr><td>Build prompts (per milestone)</td><td>v6 &sect;29 prompts 1&ndash;13</td></tr>
  <tr><td>ADRs</td><td><code>docs/adr/</code> (6 records)</td></tr>
</table>

<h2>What&rsquo;s out of scope (v1)</h2>
<ul>
  <li><strong>Multi-tenant.</strong> The audit chain and key registry are single-tenant by design (v6 &sect;7.3 documents the multi-tenant runway).</li>
  <li><strong>Persistent agent memory across sessions.</strong> Deferred (v6 &sect;4).</li>
  <li><strong>GitHub/GitLab/Linear.</strong> Bitbucket only in v1 (v6 &sect;3).</li>
  <li><strong>OpenAPI codegen for the admin REST API.</strong> Hand-typed for v1 (v6 &sect;40).</li>
</ul>

<h2>Linked artifacts</h2>
<ul>
  <li>Spec: v6 &sect;2, &sect;7, &sect;10, &sect;14, &sect;18, &sect;19, &sect;22, &sect;30</li>
  <li>ADRs: ADR-0001 (pglite), ADR-0002 (token encryption), ADR-0003 (ADF default), ADR-0004 (BB app password), ADR-0005 (audit signing)</li>
  <li>Code: <code>src/</code> &mdash; see &ldquo;Where things live&rdquo; above</li>
  <li>Jira: PCO-1 (Runtime), PCO-2 (Domain+Storage), PCO-3 (Atlassian providers), PCO-4 (VCS), PCO-7 (Audit+Policy)</li>
</ul>

<p><em>Last reviewed: 2026-04-25 by Chris.</em></p>
"""


def system_context_diagram() -> str:
    return """
<h1>System Context Diagram</h1>
<p>The diagram below shows trust boundaries (dashed) and dataflow (solid arrows). For the rendered image, see <code>docs/demo/screenshots/08-architecture-diagram.png</code> in the GitHub repo.</p>

<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[
              External callers                       External systems
              ----------------                       ----------------
                Build agent                           Jira / Confluence
                    |   (MCP/JSON-RPC)                   ^
                    v                                    |
        +-----------+-----------+                        |
        |     atl-mcp server     |                       |
        |   .---------------.    |   REST + ADF/storage   |
        |   | MCP transport |    |---------+              |
        |   '---------------'    |          \\            |
        |        |               |           \\           |
        |        v               |            v          |
        |   .---------------.    |        Bitbucket       |
        |   | Policy layer  |    |        (REST v2)       |
        |   '---------------'    |            ^          |
        |        |               |            |          |
        |        v               |            |          |
        |   .---------------.    |            |          |
        |   | Provider mux  |----------------+          |
        |   '---------------'    |                       |
        |        |               |                       |
        |        v               |                       |
        |   .---------------.    |                       |
        |   | Audit chain   |    |                       |
        |   |   (ed25519)   |    |                       |
        |   '---------------'    |                       |
        +------------------------+
                ^
                |   (admin REST)
            Operator
]]></ac:plain-text-body></ac:structured-macro>

<h2>Trust boundaries</h2>
<ol>
  <li><strong>External callers &rarr; server.</strong> Build agents authenticate at MCP session start. Operators authenticate via admin REST.</li>
  <li><strong>Server &rarr; external systems.</strong> Atlassian uses API token or OAuth 3LO; Bitbucket uses app-password or OAuth (ADR-0004). Tokens are encrypted at rest (ADR-0002) and held only in memory during request signing.</li>
  <li><strong>Audit boundary.</strong> Every state change crosses this boundary. Anything that mutates external systems generates an audit entry, signed and chained.</li>
</ol>

<p><em>Linked: Architecture Overview parent page; v6 &sect;7, &sect;22, &sect;30.</em></p>
"""


def runtime_topology() -> str:
    return """
<h1>Runtime / Deployment Topology</h1>
<p><strong>TL;DR:</strong> Single Node 20+ process, dual ports, container-deployable. Postgres in prod (Cloud SQL or RDS); pglite in dev.</p>

<h2>Process model</h2>
<ul>
  <li>One process; single event loop.</li>
  <li>Worker pool for CPU-bound work (audit signing, ADF rendering).</li>
  <li>Admin REST API on port <code>$ADMIN_PORT</code>; MCP streamable HTTP on port <code>$MCP_PORT</code>. The two are intentionally on separate ports (v6 &sect;22.2) to make firewall rules trivial.</li>
</ul>

<h2>Dependencies</h2>
<ul>
  <li>Postgres 14+ (prod). Schema lives in <code>src/storage/migrations/</code>.</li>
  <li>OpenSSL / WebCrypto for libsodium primitives (via @noble/ciphers per ADR-0002).</li>
  <li>Atlassian Cloud + Bitbucket Cloud (the systems being orchestrated).</li>
</ul>

<h2>Deploy</h2>
<ul>
  <li><code>Dockerfile</code> at repo root produces a runnable image (Node 20 alpine, non-root user).</li>
  <li>Env config per v6 &sect;20. Required: <code>ATLASSIAN_*</code>, <code>VCS_*</code>, <code>DATABASE_URL</code>, <code>AUDIT_SIGNING_KEY_REGISTRY_REF</code>.</li>
  <li>Health check: <code>GET /admin/health</code> on the admin port returns 200 + a JSON with migration version, DB connectivity, and audit-chain integrity.</li>
</ul>
"""


def storage_design() -> str:
    return stub(
        "Storage layer overview: domain entities, migrations, repository pattern, and the migration rehearsal pattern.",
        ["ADR-0001 (pglite for dev)", "v6 &sect;10 (domain model)", "<code>src/storage/migrationRunner.ts</code>", "<code>tests/integration/storage/migrationRehearsal.test.ts</code>"],
    )


def provider_layer() -> str:
    return stub(
        "Provider abstraction unifies Atlassian (Jira + Confluence) and VCS (Bitbucket). Each provider implements capability discovery, paginated reads with retry, and writes that satisfy the policy + audit contract.",
        ["v6 &sect;19", "ADR-0003 (Confluence storage default)", "ADR-0004 (Bitbucket app password)", "<code>src/providers/Provider.ts</code>"],
    )


def policy_approval_model() -> str:
    return stub(
        "Every state-changing operation gates through the policy decision layer. The current implementation is a code-policy adapter; future adapters (OPA, Cedar) plug in behind the same interface.",
        ["v6 &sect;7.2", "<code>src/security/policyDecisionLayer.ts</code>", "<code>src/security/policyAdapters/codePolicyAdapter.ts</code>"],
    )


def audit_chain_design() -> str:
    return """
<h1>Audit Chain Design</h1>
<p><strong>TL;DR:</strong> Every state change appends an audit entry. Each entry is hash-linked to the previous one and signed with ed25519. The signing key is determined by a git-ref-versioned registry. The chain is verifiable offline.</p>

<h2>Entry shape</h2>
<table>
  <tr><th>Column</th><th>Purpose</th></tr>
  <tr><td><code>id</code></td><td>UUIDv7 (sortable) primary key</td></tr>
  <tr><td><code>actor</code></td><td>Who initiated the change &mdash; build-agent session, operator account, system</td></tr>
  <tr><td><code>operation</code></td><td>Verb + object (e.g. <code>jira.issue.create</code>)</td></tr>
  <tr><td><code>payload</code></td><td>Canonical JSON of the change inputs and outputs</td></tr>
  <tr><td><code>prev_hash</code></td><td>SHA-256 of the previous entry&rsquo;s canonical serialization (incl. its signature). NULL for genesis.</td></tr>
  <tr><td><code>payload_hash</code></td><td>SHA-256 of <code>payload</code></td></tr>
  <tr><td><code>chain_hash</code></td><td>SHA-256(<code>prev_hash || payload_hash</code>)</td></tr>
  <tr><td><code>signature</code></td><td>ed25519 signature over <code>chain_hash</code></td></tr>
  <tr><td><code>key_id</code></td><td>ID of the signing key (looked up in the git-ref registry)</td></tr>
  <tr><td><code>ts</code></td><td>Server-generated timestamp</td></tr>
</table>

<h2>Verifier</h2>
<p>An offline verifier walks the chain in order, recomputes each <code>chain_hash</code>, and validates each <code>signature</code> against the key registered for that <code>key_id</code> at the relevant git-ref commit. Any mismatch surfaces with the failing entry id and the specific failure mode (chain break vs signature invalid vs key unknown).</p>

<h2>Key registry</h2>
<p>The signing-key public-half is stored in a git ref. Why git: writes are atomic, rotations produce verifiable history, and ops can verify the registry against their fork without trusting the running server. Cost: rotation requires a commit + ref update, which is an operational ceremony.</p>
<p>Trade-off accepted in ADR-0005. Open questions about tag (immutable) vs branch (mutable) registry resolved in favor of branch + log-the-rotation-event.</p>

<h2>Genesis block</h2>
<p>The first entry has <code>prev_hash = NULL</code>. This is the chicken-and-egg case &mdash; documented intentionally. The verifier handles it as a special case (and notes &ldquo;chain length 1, genesis only&rdquo; in its output).</p>

<h2>What&rsquo;s out of scope (v1)</h2>
<ul>
  <li>Per-tenant key isolation. Single-tenant only; multi-tenant runway documented in v6 &sect;7.3 and tracked as <strong>PCO-51</strong>.</li>
  <li>Master encryption-key rotation for the token store. Tracked as <strong>PCO-57</strong>.</li>
</ul>

<h2>Linked artifacts</h2>
<ul>
  <li>Spec: v6 &sect;30.1</li>
  <li>ADR: ADR-0005 (audit signing pipeline)</li>
  <li>Code: <code>src/storage/schema/auditEntries.ts</code>, <code>src/security/policyDecisionLayer.ts</code></li>
  <li>Jira: PCO-9 (flagship: implement hash linkage), PCO-48 (key registry), PCO-49 (verifier CLI)</li>
</ul>
"""


def webhook_design() -> str:
    return stub(
        "Webhook ingestion is signed (HMAC-SHA256), deduplicated by deterministic delivery ID, and normalized into a uniform change envelope before being routed.",
        ["v6 &sect;26", "<code>src/security/webhookSignatures.ts</code>", "PCO-34 (webhook signature verification)"],
    )


def definition_of_ready() -> str:
    return """
<h1>Definition of Ready</h1>
<p>A ticket is &ldquo;Ready&rdquo; when ALL of the following are true. The board WIP limit on the Ready column is 8. Tickets that don&rsquo;t meet this bar stay in Backlog.</p>
<ol>
  <li>Acceptance criteria written in Given/When/Then form.</li>
  <li>Component assigned (one of: Runtime, Domain, Storage, Providers - Atlassian, Providers - VCS, Security, Observability, Preflight, Docs, Demo Ops).</li>
  <li>Linked to an epic OR labeled <code>standalone</code>.</li>
  <li>Estimated as XS / S / M / L / XL. No story points &mdash; estimation uncertainty is honest.</li>
  <li>Risks and unknowns called out in description if non-trivial.</li>
</ol>
"""


def definition_of_done() -> str:
    return """
<h1>Definition of Done</h1>
<p>A ticket is &ldquo;Done&rdquo; when ALL of the following are true. No exceptions. If the ticket can&rsquo;t meet this bar, it should be split.</p>
<ol>
  <li>All acceptance criteria pass.</li>
  <li>Tests written first per the iron law (CLAUDE.md operating rules). No production code without a failing test first.</li>
  <li>Lint passes including <code>npm run lint:no-stdout</code> (the protocol-stream protector).</li>
  <li>If the change introduces a new design decision: an ADR is drafted in <code>docs/adr/</code> using the MADR template.</li>
  <li>Linked PR merged.</li>
  <li>Audit log entry generated for any state change in production.</li>
</ol>
"""


def test_strategy() -> str:
    return stub(
        "Three test categories: unit (domain serialization, security primitives, validators), integration (storage repositories, provider HTTP, MCP server build), lint (no-stdout enforcement). End-to-end against a live Atlassian site is gated behind an env var and not run in CI.",
        ["v6 &sect;31", "<code>tests/</code>", "PCO-23 (round-trip serialization)", "PCO-12 (lint:no-stdout regression)"],
    )


def branching_release() -> str:
    return stub(
        "Trunk-based development with short-lived feature branches. Each branch maps to one ticket. PRs require a passing test suite, a passing lint:no-stdout, and a self-review against the iron laws. Releases are tagged at milestone boundaries (v0.1 closes when M6a ships).",
    )


def runbook() -> str:
    return """
<h1>Operational Runbook</h1>
<p><strong>TL;DR:</strong> What atl-mcp is responsible for, how to tell when it&rsquo;s healthy, and what to do when it isn&rsquo;t. Three documented incidents at the bottom.</p>

<h2>What this service is responsible for</h2>
<ul>
  <li>Producing Jira+Confluence+Bitbucket workspace artifacts on demand from a project profile.</li>
  <li>Maintaining a tamper-evident audit log of every external write.</li>
  <li>Serving MCP context to build agents (resources, tools, prompts).</li>
</ul>

<h2>What this service is NOT responsible for</h2>
<ul>
  <li>Long-running agent state. Agents persist their own memory; we&rsquo;re a context provider, not a memory store (v6 &sect;4).</li>
  <li>Multi-tenant isolation. Single-tenant only in v1 (v6 &sect;7.3).</li>
</ul>

<h2>Health checks</h2>
<table>
  <tr><th>Endpoint</th><th>Returns</th><th>What it proves</th></tr>
  <tr><td><code>GET /admin/health</code></td><td>200 + JSON</td><td>Process is up; admin port is reachable</td></tr>
  <tr><td><code>GET /admin/health/db</code></td><td>200 + migration version</td><td>DB is reachable; migrations are at expected version</td></tr>
  <tr><td><code>GET /admin/health/audit</code></td><td>200 + chain length + last verified ts</td><td>Audit chain integrity verified within last N minutes</td></tr>
  <tr><td><code>GET /admin/health/upstream</code></td><td>200 + Atlassian/VCS rate-limit headroom</td><td>External systems are reachable and not rate-limited</td></tr>
</table>
<p>Contract verified by <code>tests/integration/mgmtApi.test.ts</code>.</p>

<h2>Common alerts</h2>
<ul>
  <li><strong>Migration runner stuck.</strong> Symptom: <code>/admin/health/db</code> returns &ldquo;migration applied but not recorded&rdquo;. Root cause is usually a partial migration that crashed before metadata commit. Action: inspect <code>src/storage/migrationRunner.ts</code> idempotency check; rehearse the failed migration on a snapshot before re-running.</li>
  <li><strong>Audit chain signature mismatch.</strong> Symptom: <code>/admin/health/audit</code> returns &ldquo;verifier failed at entry K&rdquo;. Action: investigate whether key rotation occurred without a registry update. Do NOT roll back &mdash; rolling back the chain is itself an audit event.</li>
  <li><strong>Atlassian API rate limit exhausted.</strong> Symptom: 429 responses spike. The retry layer in <code>src/providers/http/retry.ts</code> backs off, but if rates stay capped, queue depth grows. Action: pause the planner; investigate whether discovery is being run too aggressively.</li>
  <li><strong>OAuth 3LO refresh races.</strong> Symptom: intermittent 401s under concurrent calls. Tracked as <strong>PCO-59</strong>.</li>
  <li><strong>Stdout corruption (legacy).</strong> Symptom: MCP clients drop the connection within the first 100ms of session start. Root cause is some module wrote to stdout. The lint catches the literal form but PCO-12 documents the alias-form gap.</li>
</ul>

<h2>Common incidents</h2>

<h3>Incident A &mdash; M0 stdout leak</h3>
<p><strong>Timeline.</strong> Shipped M0 with a <code>console.log</code> in <code>src/mcp/sessionCapabilities.ts</code>. First MCP client connection failed silently. Caught when M1 added the lint:no-stdout check.</p>
<p><strong>Root cause.</strong> Protocol-level invariant (no stdout from src/) was respected by convention but not by tooling. M0 did not have the lint check.</p>
<p><strong>Fix.</strong> Removed the offending log; added <code>scripts/lint-no-stdout.mjs</code> as a pre-commit + CI check. Documented the rule in CLAUDE.md.</p>
<p><strong>How we prevent it now.</strong> Lint runs in CI; failure fails the build. <strong>PCO-12</strong> documents an open gap in the lint (alias forms slip through).</p>

<h3>Incident B &mdash; Migration applied to wrong-shaped DB</h3>
<p><strong>Timeline.</strong> A new migration assumed an indexed column existed; in dev (pglite) the index was vacuumed-out, masking the assumption.</p>
<p><strong>Root cause.</strong> Hand-applied SQL migrations couldn&rsquo;t represent &ldquo;run this against a snapshot first.&rdquo; The team ran the migration in dev, got green, and pushed. Prod failed.</p>
<p><strong>Fix.</strong> Replaced raw SQL apply with a migration runner that supports rehearsal mode (<strong>PCO-13</strong>). Rehearsal applies migrations to a temp DB populated from a prod-shaped seed, then verifies invariants before signing off.</p>
<p><strong>How we prevent it now.</strong> Rehearsal is mandatory in CI; <code>tests/integration/storage/migrationRehearsal.test.ts</code> guards against regressions.</p>

<h3>Incident C &mdash; Encryption key rotation broke token reads</h3>
<p><strong>Timeline.</strong> Master encryption key was rotated; existing token rows could no longer be decrypted.</p>
<p><strong>Root cause.</strong> The token store assumed a single active master key. There&rsquo;s no migration path for re-encrypting existing rows.</p>
<p><strong>Fix.</strong> Restored the previous key from secret storage; rotated only the &ldquo;next&rdquo; key. Documented as known limitation; <strong>PCO-57</strong> tracks the long-term fix (envelope encryption with per-row data keys).</p>
<p><strong>How we prevent it now.</strong> The runbook requires a re-encrypt drill before any master-key rotation. The drill is documented; tracked as part of PCO-57.</p>

<h2>Configuration</h2>
<p>Env vars per v6 &sect;20. Required:</p>
<ul>
  <li><code>ATLASSIAN_SITE_URL</code>, <code>ATLASSIAN_AUTH_MODE</code>, <code>ATLASSIAN_EMAIL</code>, <code>ATLASSIAN_API_TOKEN</code></li>
  <li><code>VCS_PROVIDER=bitbucket</code>, <code>BB_WORKSPACE</code>, <code>BB_APP_PASSWORD</code></li>
  <li><code>DATABASE_URL</code></li>
  <li><code>AUDIT_SIGNING_KEY_REGISTRY_REF</code></li>
  <li><code>ADMIN_PORT</code>, <code>MCP_PORT</code></li>
</ul>
<p>See <code>src/config/env.ts</code> for the canonical loader.</p>

<h2>Linked artifacts</h2>
<ul>
  <li>Code: <code>src/config/env.ts</code>, <code>src/storage/migrationRunner.ts</code></li>
  <li>Tests: <code>tests/integration/mgmtApi.test.ts</code>, <code>tests/integration/storage/migrationRehearsal.test.ts</code></li>
  <li>Spec: v6 &sect;20, &sect;22, &sect;28 (milestones)</li>
  <li>Jira: PCO-12, PCO-13, PCO-57, PCO-59</li>
</ul>

<p><em>Last reviewed: 2026-04-25 by Chris.</em></p>
"""


def health_slos() -> str:
    return stub(
        "SLOs: 99% of provisioning operations succeed end-to-end within 10s; 99.9% of audit entries are signed within 100ms of state change. Defined in v6 &sect;27.6.",
    )


def incident_response() -> str:
    return stub(
        "On-call playbook: P0 vs P1 vs P2; first response checklist; postmortem framework (CATCH &rarr; DIAGNOSE &rarr; ROOT CAUSE &rarr; FIX &rarr; SAVE &rarr; ENFORCE per v6 &sect;30.3).",
    )


def backup_restore() -> str:
    return stub(
        "Postgres backup is the responsibility of the hosting platform (Cloud SQL / RDS automated backups). Token store master key has its own rotation procedure (see runbook common incidents). Audit log is append-only and reconstructible from the chain itself.",
    )


def threat_model() -> str:
    return stub(
        "STRIDE summary: Spoofing &rarr; auth at session start; Tampering &rarr; audit chain; Repudiation &rarr; signed audit entries; Information disclosure &rarr; encrypted token store; DoS &rarr; rate limiting on the admin REST surface; Elevation of privilege &rarr; policy decision layer denies by default.",
    )


def token_storage() -> str:
    return stub(
        "Tokens are encrypted at rest with libsodium primitives via @noble/ciphers (ADR-0002). Plaintext exists only in memory during request signing. Master key lives in a secret-management system; rotation procedure is documented in the runbook (Incident C).",
        ["ADR-0002 (token encryption)", "<code>src/security/tokenEncryption.ts</code>", "<code>src/security/tokenStore.ts</code>"],
    )


def audit_threat_model() -> str:
    return stub(
        "Threat model for the audit chain: an attacker with DB write access cannot forge entries because they don&rsquo;t hold the signing key. An attacker with the signing key can forge new entries but cannot rewrite history without the registry-ref&rsquo;s entire commit history. An attacker with both is out of scope.",
    )


def webhook_verification() -> str:
    return stub(
        "Atlassian and Bitbucket webhooks are HMAC-SHA256 signed. The verifier is in <code>src/security/webhookSignatures.ts</code>. Signature verification is mandatory; unsigned or mis-signed deliveries are rejected with 401.",
    )


def adr_index() -> str:
    return """
<h1>ADR Index</h1>
<p>Architectural Decision Records, mirrored from <code>docs/adr/</code> in the GitHub repo. Each ADR uses MADR format. The markdown files are canonical; this page is a navigable index.</p>
<table>
  <tr><th>ID</th><th>Title</th><th>Status</th><th>Summary</th></tr>
  <tr><td>0000</td><td>ADR Process</td><td>Accepted</td><td>How to write and review ADRs in this repo (MADR format).</td></tr>
  <tr><td>0001</td><td>pglite for dev</td><td>Accepted</td><td>Use pglite (Postgres in WASM) for local dev so dev and prod share Postgres semantics.</td></tr>
  <tr><td>0002</td><td>Token encryption (noble-ciphers)</td><td>Accepted</td><td>Use @noble/ciphers libsodium primitives for token encryption at rest.</td></tr>
  <tr><td>0003</td><td>Confluence storage default ADF, flagged</td><td>Accepted</td><td>ADF as default Confluence body format with a flag to fall back to storage. Cost: dual renderer.</td></tr>
  <tr><td>0004</td><td>Bitbucket app password vs OAuth</td><td>Accepted</td><td>App-password as default for v1; OAuth as v2 work with documented rotation.</td></tr>
  <tr><td>0005</td><td>Audit signing pipeline</td><td>Accepted</td><td>Hash chain + ed25519 signature + git-ref versioned key registry.</td></tr>
</table>
"""


def mcp_tool_catalog() -> str:
    return stub(
        "Tools, resources, and prompts exposed by the orchestrator&rsquo;s MCP surface. Per v6 &sect;14, the surface is minimal-by-design and uses tool-collapse (one tool with action enum) where possible. Concrete tool registry is in <code>src/mcp/toolRegistry.ts</code> and <code>src/mcp/tools/</code>.",
        ["v6 &sect;14", "<code>src/mcp/toolRegistry.ts</code>", "<code>src/mcp/tools/projectPreflight.ts</code>"],
    )


def roadmap() -> str:
    return """
<h1>Roadmap + Milestones</h1>
<p>Milestone status as of 2026-04-25. Aligned with v6 &sect;28.</p>
<table>
  <tr><th>Milestone</th><th>Surface area</th><th>Status</th><th>Linked epic</th></tr>
  <tr><td>M0</td><td>Scaffold &mdash; runtime, transport, lint</td><td>Done</td><td>PCO-1</td></tr>
  <tr><td>M1</td><td>Domain model + storage + token encryption</td><td>Done</td><td>PCO-2</td></tr>
  <tr><td>M2</td><td>Atlassian providers + capability discovery</td><td>In Progress (auth+read done; capability discovery open)</td><td>PCO-3</td></tr>
  <tr><td>M3</td><td>VCS provider (Bitbucket)</td><td>In Progress (auth+REST done; worktree manager open)</td><td>PCO-4</td></tr>
  <tr><td>M4</td><td>Blueprint workflow with sampling</td><td>To Do</td><td>PCO-5</td></tr>
  <tr><td>M5</td><td>Provisioning planner</td><td>To Do</td><td>PCO-6</td></tr>
  <tr><td>M6a</td><td>Jira executor (first shippable slice)</td><td>To Do</td><td>PCO-6</td></tr>
  <tr><td>M6b</td><td>Confluence executor</td><td>To Do</td><td>PCO-6</td></tr>
  <tr><td>M6c</td><td>VCS executor</td><td>To Do</td><td>PCO-6</td></tr>
  <tr><td>M7</td><td>Context resources + packs</td><td>To Do</td><td>(future epic)</td></tr>
  <tr><td>M8</td><td>Readiness validation</td><td>To Do</td><td>(future epic)</td></tr>
  <tr><td>M9</td><td>Agent handoff</td><td>To Do</td><td>(future epic)</td></tr>
  <tr><td>M10</td><td>Webhook ingestion + subscriptions</td><td>To Do</td><td>(future epic)</td></tr>
  <tr><td>M11</td><td>Notifications, evals, hardening (audit + policy)</td><td>In Progress (audit+policy done; verifier+wrap-executors open)</td><td>PCO-7</td></tr>
</table>

<h2>Versions</h2>
<ul>
  <li><strong>v0.1 &mdash; First Shippable Slice</strong>. Closes when M6a ships. Per v6 &sect;28, M6a is the first shippable slice (Jira provisioning end-to-end).</li>
  <li><strong>v0.2 &mdash; Read-Path Demo</strong>. Closes when M7 ships (context resources + packs).</li>
</ul>
"""


def audit_findings() -> str:
    return """
<h1>Audit Findings + Remediation Summary</h1>
<p><strong>This is the most important page in the project.</strong> If you&rsquo;re a reviewer reading for self-critique, start here.</p>

<h2>Methodology</h2>
<p>Three sources fed this list:</p>
<ol>
  <li><strong>Self-review.</strong> Routine review during ADR drafting and milestone sign-off.</li>
  <li><strong>Repo-extraction findings.</strong> A delta-audit comparing the v6 spec to the implementation, captured in <code>repo-extraction-findings.md</code> at repo root.</li>
  <li><strong>Security review.</strong> Pass over the security-relevant code (token store, audit chain, policy layer, webhook verification) using the security-review skill.</li>
</ol>

<h2>Findings</h2>
<table>
  <tr><th>ID</th><th>Title</th><th>Severity</th><th>Status</th><th>Linked Jira</th></tr>
  <tr><td>F-01</td><td>console.log in src/mcp/sessionCapabilities.ts shipped in M0</td><td>High</td><td>Fixed</td><td>PCO-16</td></tr>
  <tr><td>F-02</td><td>lint:no-stdout misses dynamic process.stdout.write aliases</td><td>Medium</td><td>Acknowledged</td><td>PCO-12</td></tr>
  <tr><td>F-03</td><td>Token store doesn&rsquo;t rotate the master encryption key</td><td>High</td><td>Deferred</td><td>PCO-57</td></tr>
  <tr><td>F-04</td><td>ADF renderer drops nested table cells on round-trip</td><td>Medium</td><td>Acknowledged</td><td>PCO-58</td></tr>
  <tr><td>F-05</td><td>Audit chain genesis block has no signature (chicken-and-egg)</td><td>Low</td><td>Documented intentionally</td><td>(in ADR-0005)</td></tr>
  <tr><td>F-06</td><td>OAuth 3LO refresh races with concurrent calls</td><td>Medium</td><td>Acknowledged</td><td>PCO-59</td></tr>
  <tr><td>F-07</td><td>No integration test exercises a 429-then-success retry path</td><td>Medium</td><td>Fixed</td><td>(commit covered by PCO-3)</td></tr>
  <tr><td>F-08</td><td>Pagination cursor in Confluence v2 silently truncates at 250 entries</td><td>Medium</td><td>Acknowledged</td><td>PCO-30</td></tr>
  <tr><td>F-09</td><td>Storage migration rehearsal can&rsquo;t represent vacuumed-row schemas</td><td>Low</td><td>Deferred</td><td>PCO-56</td></tr>
  <tr><td>F-10</td><td>Race in planner when two sessions provision overlapping namespaces</td><td>High</td><td>Deferred (M5 dependency)</td><td>PCO-46</td></tr>
  <tr><td>F-11</td><td>Per-tenant key isolation not implemented (multi-tenant runway)</td><td>Medium (single-tenant), High (multi-tenant)</td><td>Out of v1 scope</td><td>PCO-51 (spike)</td></tr>
  <tr><td>F-12</td><td>Several domain modules previously imported <code>console</code></td><td>Low</td><td>Fixed</td><td>PCO-16</td></tr>
  <tr><td>F-13</td><td>Confluence space provisioning uses v1 API; v2 has different shape</td><td>Low</td><td>Acknowledged (the v2 endpoint had a representation bug at time of writing; revisit)</td><td>(this Demo Ops epic)</td></tr>
  <tr><td>F-14</td><td>Workflow has 3 statuses not 5 (next-gen Kanban template constraint)</td><td>Low</td><td>Acknowledged in seed plan</td><td>(this Demo Ops epic)</td></tr>
  <tr><td>F-15</td><td>Hand-applied SQL migrations couldn&rsquo;t represent &ldquo;run against a snapshot first&rdquo;</td><td>High</td><td>Fixed</td><td>PCO-13</td></tr>
</table>

<h2>The most embarrassing finding</h2>

<h3>F-01: console.log in src/mcp/sessionCapabilities.ts shipped in M0</h3>
<p>I shipped M0 with a <code>console.log</code> in <code>src/mcp/sessionCapabilities.ts</code> and didn&rsquo;t notice until M1 added the <code>lint:no-stdout</code> check. The first MCP client connection failed silently because stdout corruption is invisible to the writer.</p>
<p>This is a clean example of why protocol-level invariants must be encoded as automated checks <em>before</em> any production code that depends on them. The CLAUDE.md operating rule (&ldquo;never write to stdout from src/&rdquo;) was respected by convention but not by tooling. M0 didn&rsquo;t have the lint check, so the convention slipped.</p>
<p>The lesson generalized into the overall iron law from CLAUDE.md: invariants are tooling, not vibes. Everywhere else in the project, I treat &ldquo;the rule must be enforced&rdquo; as a tooling requirement, not a documentation one. The lint:no-stdout check is the most-tested CI rule in the project precisely because of this incident.</p>

<h2>What&rsquo;s deferred and why</h2>
<ul>
  <li><strong>F-03 (master key rotation)</strong>. Requires envelope encryption with per-row data keys. Significant refactor; not justified for single-tenant v1. Will revisit when multi-tenant runway opens (v6 &sect;7.3).</li>
  <li><strong>F-09 (rehearsal vacuumed-row schemas)</strong>. Pglite&rsquo;s vacuum behavior differs subtly from full Postgres. Acceptable for v1 because the gap is documented and the rehearsal still catches 95%+ of issues.</li>
  <li><strong>F-10 (planner race)</strong>. Depends on M5 (planner) being implemented first. Will land with PHASE-STATE.json concurrency control per v6 &sect;6.1.</li>
  <li><strong>F-11 (per-tenant isolation)</strong>. Out of v1 scope by design. Multi-tenant runway documented in v6 &sect;7.3.</li>
</ul>

<h2>What I&rsquo;d do differently if starting over</h2>
<p>Three things.</p>
<ol>
  <li><strong>Lint:no-stdout in M0.</strong> The protocol invariant should have been the very first CI check, before the first source line. Putting it in M1 cost real reliability.</li>
  <li><strong>Migration runner in M1, not M2.</strong> The hand-applied migrations of M1 generated F-15. The runner should have been built first.</li>
  <li><strong>Demo plan before milestone 0.</strong> The dogfooding frame should drive what gets built first. I&rsquo;m reverse-engineering the demo from completed milestones; if I&rsquo;d started with the demo target, I&rsquo;d have prioritized different surfaces.</li>
</ol>

<h2>Linked artifacts</h2>
<ul>
  <li>Methodology source: <code>repo-extraction-findings.md</code> in repo root</li>
  <li>Tracked Jira tickets: PCO-12, PCO-13, PCO-16, PCO-30, PCO-46, PCO-51, PCO-56, PCO-57, PCO-58, PCO-59</li>
  <li>ADRs: ADR-0001, ADR-0002, ADR-0003, ADR-0004, ADR-0005</li>
  <li>Spec sections that document deferred/out-of-scope items: v6 &sect;3, &sect;4, &sect;7.3, &sect;28</li>
</ul>

<p><em>Last reviewed: 2026-04-25 by Chris.</em></p>
"""


def known_limitations() -> str:
    return """
<h1>Known Limitations</h1>
<p>Things this system explicitly does not do well, with rationale and (where applicable) the milestone or ticket where it gets fixed.</p>

<h2>Single-tenant only</h2>
<p>The audit chain key registry, the token store, and the storage schema are all single-tenant. Multi-tenant runway is documented in v6 &sect;7.3 and tracked as <strong>PCO-51</strong> (spike). This is the most significant limitation for &ldquo;could you ship this to prod with multiple customers?&rdquo;</p>

<h2>Atlassian-only (in v1)</h2>
<p>Bitbucket Cloud only for v1. GitHub, GitLab, and Bitbucket Data Center / Server are post-v1 (v6 &sect;3 non-goals). The provider abstraction (<code>src/providers/</code>) is designed to add new VCS providers, but capacity is not.</p>

<h2>No persistent agent memory</h2>
<p>This is a context provider, not an agent memory store. Per-session memory is the agent&rsquo;s responsibility (v6 &sect;4 non-goals; see <code>docs/partners/hindsight.md</code> for the considered approach).</p>

<h2>Workflow has 3 statuses, not 5</h2>
<p>The seed Jira project uses Jira&rsquo;s next-gen Kanban template, which provides To Do / In Progress / Done. The original plan called for 5 statuses (Backlog / Ready / In Progress / Review / Done). Adapted because customizing the workflow is theater unless wired to gating logic. The Definition of Ready and Definition of Done pages serve the gating role instead.</p>

<h2>Master key rotation</h2>
<p>The token store does not rotate the master encryption key. PCO-57 documents the long-term fix (envelope encryption with per-row data keys). Workaround: master key rotation requires a re-encrypt drill (documented in the runbook).</p>

<h2>Lint gap on stdout aliases</h2>
<p>PCO-12 documents that <code>lint:no-stdout</code> doesn&rsquo;t catch alias forms (<code>const w = process.stdout</code>). Replacement is an AST-walk lint instead of regex. Severity is medium because the literal form (which IS caught) is the path normal coding takes.</p>
"""


def glossary() -> str:
    return """
<h1>Glossary</h1>
<dl>
  <dt><strong>MCP</strong></dt><dd>Model Context Protocol. The protocol agentic AI build agents use to consume tools, resources, and prompts. atl-mcp implements the server side.</dd>
  <dt><strong>ADF</strong></dt><dd>Atlassian Document Format. JSON tree representation of rich content used by Confluence (and Jira issue descriptions). Round-trips cleanly; preferred for new content.</dd>
  <dt><strong>Storage format</strong></dt><dd>Confluence&rsquo;s legacy XHTML-ish body format. Required for some macros; supported as a fallback per ADR-0003.</dd>
  <dt><strong>ed25519</strong></dt><dd>Edwards-curve digital signature algorithm. Public-key signature with small keys, fast verification, no PRNG needed for signing. Used in the audit chain (v6 &sect;30.1).</dd>
  <dt><strong>The four agent modes</strong></dt><dd>Orchestrator, Builder, Reviewer, Operator. Per v6 &sect;14.1, the orchestrator emits skills tailored to the agent&rsquo;s mode.</dd>
  <dt><strong>Readiness rubric</strong></dt><dd>The 6-category deterministic score + 4-tier LLM-judged verdict that gates handoff. Defined in v6 &sect;17.</dd>
  <dt><strong>Iron laws</strong></dt><dd>Two non-negotiables in CLAUDE.md: (1) never claim a task done without verification evidence, (2) never write production code without a failing test first when adding behavior.</dd>
  <dt><strong>Dogfooding frame</strong></dt><dd>The portfolio strategy: use atl-mcp to seed atl-mcp&rsquo;s own Jira+Confluence project. The structure of this space is the demonstration.</dd>
  <dt><strong>Genesis block</strong></dt><dd>The first entry in the audit chain. <code>prev_hash</code> is null. Verifier handles it as a special case.</dd>
  <dt><strong>PHASE-STATE.json</strong></dt><dd>The on-disk concurrent-safe state file for the project state machine, per v6 &sect;6.1.</dd>
</dl>
"""


def demo_walkthrough() -> str:
    return """
<h1>Demo Walkthrough</h1>
<p>For reviewers. Three lengths; pick whichever matches the time you have.</p>
<ul>
  <li><a href="#">60-Second Pitch</a></li>
  <li><a href="#">5-Minute Tour</a></li>
  <li><a href="#">15-Minute Deep Dive</a></li>
</ul>
<p>Backing material:</p>
<ul>
  <li>Architecture Overview &mdash; the top-line system explanation.</li>
  <li>Audit Findings + Remediation Summary &mdash; the most signal-dense page.</li>
  <li>The PCO Jira project &mdash; the dogfooding payoff.</li>
</ul>
<p>The mirror in the GitHub repo (<code>docs/demo/</code>) holds the same scripts so a reader without Confluence access still sees everything.</p>
"""


def tour_60() -> str:
    return """
<h1>60-Second Pitch</h1>
<p><strong>Read time:</strong> ~55 seconds at conversational pace.</p>
<blockquote>
<p>I built an MCP server that turns raw project requirements into agent-ready Jira, Confluence, and Bitbucket workspaces. The Jira project and Confluence space you&rsquo;re about to see were generated by it, from its own requirements.</p>
<p>The repo has the spec it implements &mdash; a v6, ~2,400 lines. It has 42 partner integration guides synthesized into the design. It has six ADRs justifying the harder decisions, and an audit findings page where I document what I got wrong.</p>
<p>If you only have a minute, three things are worth a look: the architecture diagram, the screenshot of the Jira board, and &mdash; most importantly &mdash; the audit findings summary. That last one is where I document my own mistakes. It&rsquo;s the most signal-dense page in the project.</p>
</blockquote>
"""


def tour_5() -> str:
    return """
<h1>5-Minute Tour</h1>
<p>Five sections, ~1 minute each. Hold questions to the end of each section.</p>
<ol>
  <li><strong>(0:00&ndash;0:30) Pitch and frame.</strong> The 60-second pitch above, minus the closing bullets.</li>
  <li><strong>(0:30&ndash;1:30) Architecture.</strong> Open the Architecture Overview page. Read the TL;DR. Show the system context diagram. Name the three trust boundaries: external callers, server, external systems. Mention the dual-port HTTP transport (admin REST + MCP streamable HTTP, v6 &sect;22). Mention the policy decision layer and the audit chain. Don&rsquo;t drill in unless asked.</li>
  <li><strong>(1:30&ndash;3:00) Generated Jira project.</strong> Switch to Jira (PCO board). Note the swimlanes by component, the WIP-discipline columns. Open the &ldquo;Audit + Policy Enforcement&rdquo; epic. Open the flagship story PCO-9 under it (audit chain hash linkage). Read the description. Note the linked ADR-0005 and v6 &sect;30.1. Pause and say: <em>&ldquo;all of this &mdash; the structure of the project, the issue types, the workflow, the components &mdash; came out of running the orchestrator on its own profile.&rdquo;</em></li>
  <li><strong>(3:00&ndash;4:00) Confluence space.</strong> Switch to Confluence (this space). Show the page tree. Open the Operational Runbook page. Show the &ldquo;Common Incidents&rdquo; section with three documented incidents. Open the Audit Findings page. Don&rsquo;t read individual findings; just show the table.</li>
  <li><strong>(4:00&ndash;5:00) Self-critique.</strong> Stay on the audit findings page. Pick F-01 (the M0 stdout leak). Read the embarrassing-finding paragraph aloud. End with the lesson: <em>&ldquo;invariants are tooling, not vibes.&rdquo;</em></li>
</ol>
"""


def tour_15() -> str:
    return """
<h1>15-Minute Deep Dive</h1>
<p>Seven sections plus Q&amp;A buffer. The 5-minute tour, expanded with spec walkthrough, ADR drill-in, and a real code-walk to defuse the &ldquo;did you actually write this?&rdquo; question.</p>
<ol>
  <li><strong>(0:00&ndash;1:00) Pitch.</strong></li>
  <li><strong>(1:00&ndash;3:00) Spec walkthrough.</strong> Open the v6 spec. Show the 40+ section ToC. Drill into v6 &sect;17 (Readiness Rubric). Walk through: deterministic 6-category score, LLM-judged 4-tier verdict, project-level rubric, issue-level rubric, 5-section skill format. Why &sect;17? It&rsquo;s the section most likely to demonstrate that the spec has thought through measurable quality, not just architectural flourish.</li>
  <li><strong>(3:00&ndash;6:00) Architecture deep dive.</strong> Architecture Overview page, then drill into the audit chain. Open ADR-0005. Walk through hash chain &rarr; ed25519 &rarr; key registry &rarr; genesis &rarr; rotation. Then show <code>src/storage/schema/auditEntries.ts</code> to confirm the implementation matches the design.</li>
  <li><strong>(6:00&ndash;9:00) Generated artifacts.</strong> Same as 5-minute version; plus drill into the Spike PCO-11 (Confluence ADF vs storage), because its closure is ADR-0003 and the dual-representation discussion is genuinely hard.</li>
  <li><strong>(9:00&ndash;11:00) Implementation.</strong> Switch to a terminal in the repo. Run <code>npm run lint:no-stdout</code>. Show <code>scripts/lint-no-stdout.mjs</code>. Run <code>npm test</code>. Open <code>src/storage/migrationRunner.ts</code> and walk through it line by line. <em>This is the &ldquo;I really wrote this&rdquo; moment &mdash; make it count.</em></li>
  <li><strong>(11:00&ndash;13:00) Self-critique + roadmap.</strong> Audit Findings page. Walk F-01 in full. Open Roadmap. Be explicit about what&rsquo;s not done.</li>
  <li><strong>(13:00&ndash;15:00) Q&amp;A buffer.</strong> Use the time. If they have no questions, ask: <em>&ldquo;what would you want to dig into more?&rdquo;</em></li>
</ol>
"""


# ---------------------------------------------------------------------------
# Page tree definition
# ---------------------------------------------------------------------------
# Tuples of (title, parent_title_or_None_for_root, body_fn)
# Parent of None means parent = HOMEPAGE_ID.

PAGES = [
    # Top-level (under homepage)
    ("Project Overview", None, project_overview),
    ("Product Brief", "Project Overview", product_brief),
    ("Architecture Overview", "Project Overview", architecture_overview),
    ("Engineering Practice", "Project Overview", lambda: stub("Process documentation: how work moves through the board, what tests we require, how releases are cut. Children: Definition of Ready, Definition of Done, Test Strategy, Branching + Release Process.")),
    ("Operations", "Project Overview", lambda: stub("Operational documentation: runbook, health checks, SLOs, incident response, backup. Children: Operational Runbook, Health Checks + SLOs, Incident Response, Backup + Restore.")),
    ("Security", "Project Overview", lambda: stub("Security documentation: threat model, token storage, audit chain threat model, webhook verification.")),
    ("ADR Index", "Project Overview", adr_index),
    ("MCP Tool Catalog", "Project Overview", mcp_tool_catalog),
    ("Roadmap + Milestones", "Project Overview", roadmap),
    ("Audit Findings + Remediation Summary", "Project Overview", audit_findings),
    ("Known Limitations", "Project Overview", known_limitations),
    ("Glossary", "Project Overview", glossary),
    ("Demo Walkthrough", "Project Overview", demo_walkthrough),

    # Architecture children
    ("System Context Diagram", "Architecture Overview", system_context_diagram),
    ("Runtime / Deployment Topology", "Architecture Overview", runtime_topology),
    ("Storage + Migration Design", "Architecture Overview", storage_design),
    ("Provider Layer", "Architecture Overview", provider_layer),
    ("Policy + Approval Model", "Architecture Overview", policy_approval_model),
    ("Audit Chain Design", "Architecture Overview", audit_chain_design),
    ("Webhook Ingestion Design", "Architecture Overview", webhook_design),

    # Engineering Practice children
    ("Definition of Ready", "Engineering Practice", definition_of_ready),
    ("Definition of Done", "Engineering Practice", definition_of_done),
    ("Test Strategy", "Engineering Practice", test_strategy),
    ("Branching + Release Process", "Engineering Practice", branching_release),

    # Operations children
    ("Operational Runbook", "Operations", runbook),
    ("Health Checks + SLOs", "Operations", health_slos),
    ("Incident Response", "Operations", incident_response),
    ("Backup + Restore", "Operations", backup_restore),

    # Security children
    ("Threat Model", "Security", threat_model),
    ("Token Storage", "Security", token_storage),
    ("Audit Chain Threat Model", "Security", audit_threat_model),
    ("Webhook Verification", "Security", webhook_verification),

    # Demo Walkthrough children
    ("60-Second Pitch", "Demo Walkthrough", tour_60),
    ("5-Minute Tour", "Demo Walkthrough", tour_5),
    ("15-Minute Deep Dive", "Demo Walkthrough", tour_15),
]


def main() -> None:
    print(f"Seeding Confluence space {SPACE_KEY} ({SPACE_ID})...", flush=True)
    titles = list_existing_titles()
    print(f"  {len(titles)} existing pages (skipping these)", flush=True)

    # Title -> id, including pages we just created.
    title_to_id: dict[str, str] = dict(titles)

    for title, parent_title, body_fn in PAGES:
        if title in title_to_id:
            print(f"  exists: {title}")
            continue
        parent_id = HOMEPAGE_ID if parent_title is None else title_to_id.get(parent_title)
        if parent_id is None:
            print(f"  SKIP {title!r} (parent {parent_title!r} not found)", file=sys.stderr)
            continue
        try:
            body = body_fn()
            new_id = create_page(title, parent_id, body)
            title_to_id[title] = new_id
            print(f"  created: {title}  (id={new_id}, parent={parent_id})")
        except Exception as e:
            print(f"  FAILED {title!r}: {e}", file=sys.stderr)

    print("Done.", flush=True)


if __name__ == "__main__":
    main()
